### ISSUE TITLE
Maria DB slaves fail to start 

### ISSUE THREAD

**Issue by ThePetRepublic** [bitnami/bitnami-docker#16]
for some reason the Maria DB slaves fail to start
mariadb-master-0hjpr     1/1       Running            0          38m
mariadb-slave-513dq      0/1       CrashLoopBackOff   10         37m
mariadb-slave-hthsm      0/1       CrashLoopBackOff   11         37m
mariadb-slave-zsgzk      0/1       CrashLoopBackOff   11         37m

**Comment by GeoffreyEmery** [comment]
+2 on this.

**Comment by sameersbn** [comment]
I didn't face any problems deploying a mariadb cluster on kubernetes using our [mariadb-cluster](https://github.com/bitnami/charts/tree/master/mariadb-cluster) chart for Helm Classic.

@ThePetRepublic @GeoffreyEmery Could you please share your kubernetes manifest files so that we can reproduce and debug this issue?

**Comment by GeoffreyEmery** [comment]
hmm.. i deleted my instance wasn't sure how active you were going to be on this. i can recreate it today. Quick search on the interweb doens't bring up kubernetes manifest file can  you explain what you mean. if this is the yaml file used to create the instance it didn't change the git repo's version. Just the deployed what you had.

**Comment by sameersbn** [comment]
@GeoffreyEmery My manifest I meant the kubernetes YML files. Can you please indicate which tutorial  you were following?

**Comment by GeoffreyEmery** [comment]
Here you go.. didn't realize this was posted as a issue to the main repo. 
https://github.com/bitnami/bitnami-docker/tree/master/gke/wordpress

**Comment by GeoffreyEmery** [comment]
here is the yml file https://github.com/bitnami/bitnami-docker/blob/master/gke/wordpress/mariadb-slave-controller.yml

**Comment by sameersbn** [comment]
The issue has been resolved. Some changes introduced in the latest kubernetes versions caused the issue. Let us know how it goes 😄
