### ISSUE TITLE
Mariadb Slaves CrashLoopBackOff   

### ISSUE THREAD

**Issue by somadona** [bitnami/bitnami-docker#19]
Hi,

MariaDB slaves start and show running, then after couple minutes it shows "CrashLoopBackOff" without back to running again ? any help on that  

tutorial used: https://github.com/bitnami/bitnami-docker/tree/master/gke/wordpress

**Comment by prydonius** [comment]
cc @sameersbn

**Comment by somadona** [comment]
Hello @sameersbn, thanks it works now :)

One more question please where I can find wordpress default install directory ?

**Comment by sameersbn** [comment]
Wordpress is installed at `/app` path in the containers. You may want to take a look at the Dockerfiles
 - https://github.com/bitnami/bitnami-docker/blob/master/gke/wordpress/dockerfiles/wordpress-php/Dockerfile
 - https://github.com/bitnami/bitnami-docker/blob/master/gke/wordpress/dockerfiles/wordpress-apache/Dockerfile

Please note if you are interested in setting up Wordpress in production you may want to take a look at the [bitnami/wordpress](https://github.com/bitnami/bitnami-docker-wordpress) image. 

We have also contributed a [wordpress chart](https://github.com/kubernetes/charts/tree/master/stable/wordpress) to the official [kubernetes/charts](https://github.com/kubernetes/charts/) repo and is a much easier way to deploy a simple wordpress blog on any kubernetes cluster.

**Comment by sameersbn** [comment]
@somadona Closing this report. Do let us know if you have any further queries. We'll be happy to support you.
