### ISSUE TITLE
Unnecessary double folder?

### ISSUE THREAD

**Issue by MelvinLoos** [bitnami/bitnami-docker#8]
At bitnami-docker/gke/lamp/dockerfiles/myapp-apache/ we see the same code folder as is present in the bitnami-docker/gke/lamp/dockerfiles/myapp-php/ folder. Both Dockerfiles are pretty much identical and both load the code folder in their container. As far as I understand the application code is only necesarry inside the php container as this is the one that interprets the php code (hence the name) but please correct me if I am wrong. As a developer I would like to prevent duplication as much as possible so if anyone could explain, why is this done exactly?

**Comment by sameersbn** [comment]
It's true that the php code need to only be present in the php container. As you might be aware that static file assets such as images, js scripts, etc. will not be served by php and have to be served through the web server (apache in this case). This is the reason why the code is copied into both the containers.

Generally you would have the php and apache components in the same container. In the tutorial we  demonstrate isolation of concerns by moving php and apache in separate containers. That being said at the moment its not possible to run both php and apache in the same container using bitnami's stock images.

We will resolve this problem with the [stacksmith](stacksmith.bitnami.com) offering.

**Comment by MelvinLoos** [comment]
Would it be an idea to make a separate container which mounts a volume (an emptyDir probably?) with read/write access, to which it downloads the code from a git repo and then mount that same volume on both the Apache and PHP containers (with read-only access)? That would prevent the code duplication.
In the stacksmith alternative it probably builds a new image for each update right? Might also be a handy way, because then you can define the new image and update the environment through a rolling update.

**Comment by prydonius** [comment]
I think the issue there is Kubernetes doesn't support mounting volumes from other containers. I think the only way to do what you describe would be to use a persistent disk that can be shared between the containers.

Yeah, that's the idea for Stacksmith, and you would generally automate that pipeline using your CI.

**Comment by sameersbn** [comment]
@MelvinLoos you have a good point regarding pulling code from a git repo though. @prydonius kubernetes now has a builtin git-repo volume that allows you to do just that.

**Comment by prydonius** [comment]
@sameersbn ah yes, you're right - would be good to see if we could use that here.

**Comment by sameersbn** [comment]
@prydonius yep we could that for demonstration purposes.

**Comment by MelvinLoos** [comment]
@prydonius, ah yes persistent disk is what I meant.
@sameersbn, awesome I didn't know that! That would be a great solution. What version did they add that?
